aws_region="us-east-1"
stack="terraform-workshop"
fargate-task-service-role="terraform-workshop-role"
aws_ecr="petclinic"
aws_profile="default"
source_repo_name="petclinic"
source_repo_branch="master"
image_repo_name="petclinic"