aws_region="eu-central-1"
stack="cloud-bootstrap"
fargate-task-service-role="cloud-bootstrap-role"
aws_ecr="cloud-bootstrap"
aws_profile="default"
source_repo_name="cloud-bootstrap"
source_repo_branch="master"
image_repo_name="cloud-bootstrap"